import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
// Default-import + destructure — @coral-xyz/anchor is CJS; Node's static
// named-export detection for ESM-importing-CJS can silently fail to see
// some of its exports (empirically true for BN, see publishToChain.ts) even
// though they're real at runtime, so every real (non-type-only) import from
// this package uses this pattern rather than relying on that detection.
import anchorPkg, { type Program, type Wallet } from "@coral-xyz/anchor";
import type { Connection } from "@solana/web3.js";
import type { DecentralizedNotes } from "./idl/decentralized_notes.js";

const { AnchorProvider, Program: ProgramCtor } = anchorPkg;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * The IDL JSON (not the .ts type-helper) — Anchor's `Program` constructor
 * needs the raw JSON at runtime; `DecentralizedNotes` is only a compile-time
 * type. Both files are committed here (see IMPLEMENTATION_PLAN.md Phase 3),
 * regenerated by `anchor build` whenever the program changes.
 */
function loadIdl(): DecentralizedNotes {
  const raw = readFileSync(path.join(__dirname, "idl/decentralized_notes.json"), "utf8");
  return JSON.parse(raw) as DecentralizedNotes;
}

export function createProgram(connection: Connection, wallet: Wallet): Program<DecentralizedNotes> {
  const provider = new AnchorProvider(connection, wallet, { commitment: "confirmed" });
  return new ProgramCtor<DecentralizedNotes>(loadIdl(), provider);
}

export type { DecentralizedNotes };
