import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import path from "node:path";
import type { Program, Wallet } from "@coral-xyz/anchor";
import type { Connection } from "@solana/web3.js";
import type { DecentralizedNotes } from "./idl/decentralized_notes.js";

// @coral-xyz/anchor is CJS. A default *import* of a CJS package is handled
// by whichever ESM loader hook is active in the process — plain `node` and
// `tsx` disagree on the interop convention (confirmed empirically: this
// exact compiled file works under `node dist/worker.js` but the default
// import resolves to `undefined` under `tsx scripts/*.ts`, since tsx's
// esbuild-based loader doesn't synthesize the same default). `createRequire`
// sidesteps ESM interop entirely — it's Node's real CJS require function,
// loader-agnostic, so it behaves identically everywhere.
const require = createRequire(import.meta.url);
const { AnchorProvider, Program: ProgramCtor } = require("@coral-xyz/anchor") as typeof import("@coral-xyz/anchor");

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * The IDL JSON (not the .ts type-helper) — Anchor's `Program` constructor
 * needs the raw JSON at runtime; `DecentralizedNotes` is only a compile-time
 * type. Both files are committed here (see IMPLEMENTATION_PLAN.md Phase 3),
 * regenerated by `anchor build` whenever the program changes.
 */
function loadIdl(): DecentralizedNotes {
  const raw = readFileSync(path.join(__dirname, "idl/decentralized_notes.json"), "utf8");
  return JSON.parse(raw) as DecentralizedNotes;
}

export function createProgram(connection: Connection, wallet: Wallet): Program<DecentralizedNotes> {
  const provider = new AnchorProvider(connection, wallet, { commitment: "confirmed" });
  return new ProgramCtor<DecentralizedNotes>(loadIdl(), provider);
}

export type { DecentralizedNotes };
