import { useState } from "react";
import { useAuditLog } from "@/hooks/useAdmin";
import { EmptyState } from "@/components/EmptyState";
import { CardSkeletonList } from "@/components/CardSkeleton";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { AdminDateControls, AdminPagination, applyDatePreset, type AdminDatePreset, type AdminListState } from "@/components/admin/AdminTableControls";

function humanize(action: string) { return action.replace(/_/g, " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase()); }
export function AuditLogPage() {
  const [preset, setPreset] = useState<AdminDatePreset>("all"); const [state, setState] = useState<AdminListState>({ page: 1, pageSize: 25 }); const { data, isLoading } = useAuditLog(state);
  const onChange = (next: Partial<AdminListState>) => setState((current) => ({ ...current, ...next })); const onPreset = (next: AdminDatePreset) => { setPreset(next); setState((current) => ({ ...current, ...applyDatePreset(next), page: 1 })); };
  return <div className="px-4 py-6 md:px-8"><AdminPageHeader title="Audit log" description="Every moderation and admin action, newest first." /><div className="mt-5"><AdminDateControls preset={preset} state={state} onPresetChange={onPreset} onChange={onChange} /></div>{isLoading && <div className="mt-6"><CardSkeletonList /></div>}{!isLoading && data?.data.length === 0 && <EmptyState title="Nothing logged yet" description="Moderation and admin actions will show up here." />}{data && data.data.length > 0 && <><div className="mt-6 overflow-x-auto rounded-md border border-border bg-surface"><table className="w-full min-w-[54rem] text-sm"><thead className="border-b border-border bg-muted/50 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="w-14 px-4 py-3">#</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Actor</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">Time</th></tr></thead><tbody>{data.data.map((entry, index) => <tr key={entry.id} className="border-b border-border last:border-0"><td className="px-4 py-3 text-muted-foreground">{(state.page - 1) * state.pageSize + index + 1}</td><td className="px-4 py-3 font-medium">{humanize(entry.action)}</td><td className="px-4 py-3 text-muted-foreground">{entry.actor?.email ?? "System"}</td><td className="px-4 py-3 text-muted-foreground">{entry.targetType ? `${entry.targetType} ${entry.targetId}` : "—"}</td><td className="px-4 py-3 text-muted-foreground">{new Date(entry.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div><AdminPagination state={state} total={data.meta.total} onChange={onChange} /></>}</div>;
}
