import { useState } from "react";
import { Link } from "react-router-dom";
import { useBlockchainJobs, useRetryBlockchainJob, type BlockchainJob } from "@/hooks/useAdmin";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EmptyState } from "@/components/EmptyState";
import { CardSkeletonList } from "@/components/CardSkeleton";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { AdminDateControls, AdminPagination, applyDatePreset, type AdminDatePreset, type AdminListState } from "@/components/admin/AdminTableControls";

const statuses = ["ALL", "PENDING", "PROCESSING", "PROCESSED", "FAILED"] as const;
function Retry({ job }: { job: BlockchainJob }) { const retry = useRetryBlockchainJob(); return job.status === "FAILED" ? <Button size="sm" variant="outline" disabled={retry.isPending} onClick={() => retry.mutate({ id: job.id })}>{retry.isPending ? "Retrying…" : "Retry"}</Button> : <span className="text-muted-foreground">—</span>; }
export function BlockchainJobsPage() {
  const [status, setStatus] = useState<(typeof statuses)[number]>("ALL"); const [preset, setPreset] = useState<AdminDatePreset>("all"); const [state, setState] = useState<AdminListState>({ page: 1, pageSize: 25 }); const { data, isLoading } = useBlockchainJobs(state, status === "ALL" ? undefined : status);
  const onChange = (next: Partial<AdminListState>) => setState((current) => ({ ...current, ...next })); const onPreset = (next: AdminDatePreset) => { setPreset(next); setState((current) => ({ ...current, ...applyDatePreset(next), page: 1 })); };
  return <div className="px-4 py-6 md:px-8"><AdminPageHeader title="Blockchain jobs" description="The publishing queue and manual recovery controls." /><div className="mt-5 flex flex-wrap gap-3"><Tabs value={status} onValueChange={(value) => { setStatus(value as typeof status); setState((current) => ({ ...current, page: 1 })); }}><TabsList>{statuses.map((item) => <TabsTrigger key={item} value={item}>{item}</TabsTrigger>)}</TabsList></Tabs></div><div className="mt-4"><AdminDateControls preset={preset} state={state} onPresetChange={onPreset} onChange={onChange} /></div>{isLoading && <div className="mt-6"><CardSkeletonList /></div>}{!isLoading && data?.data.length === 0 && <EmptyState title="No jobs" description="Nothing matches this filter." />}{data && data.data.length > 0 && <><div className="mt-6 overflow-x-auto rounded-md border border-border bg-surface"><table className="w-full min-w-[60rem] text-sm"><thead className="border-b border-border bg-muted/50 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="w-14 px-4 py-3">#</th><th className="px-4 py-3">Publication</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Attempts</th><th className="px-4 py-3">Last updated</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{data.data.map((job, index) => <tr key={job.id} className="border-b border-border last:border-0"><td className="px-4 py-3 text-muted-foreground">{(state.page - 1) * state.pageSize + index + 1}</td><td className="px-4 py-3">{job.publication ? <Link className="font-medium text-primary underline" to={`/p/${job.publicationId}`}>{job.publication.title}</Link> : job.publicationId}</td><td className="px-4 py-3"><span className="rounded-full bg-muted px-2 py-0.5 text-xs">{job.status}</span></td><td className="px-4 py-3 text-muted-foreground">{job.attempts}/{job.maxAttempts}</td><td className="px-4 py-3 text-muted-foreground">{new Date(job.updatedAt).toLocaleString()}</td><td className="px-4 py-3 text-right"><Retry job={job} /></td></tr>)}</tbody></table></div><AdminPagination state={state} total={data.meta.total} onChange={onChange} /></>}</div>;
}
