import { useState } from "react";
import { hasPermission, Permission } from "@noteschain/shared";
import { useCurrentUser } from "@/hooks/useAuth";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { Button } from "@/components/ui/button";
import { MutationError } from "@/components/admin/MutationError";
import { useCampaignAction, useCampaignPreview, useCampaigns, useCreateCampaign, type CampaignInput } from "@/hooks/useAdmin";

function futureLocalDate(minutes = 30) { const value = new Date(Date.now() + minutes * 60_000); value.setSeconds(0, 0); return value.toISOString().slice(0, 16); }
const initial = (): CampaignInput => ({ name: "", objective: "ANNOUNCEMENT", title: "", body: "", deepLink: "/explore", audience: { target: "SIGNED_IN" }, schedule: { scheduledAt: futureLocalDate(), recurring: false, timeZone: "Asia/Karachi" } });

export function CampaignsPage() {
  const user = useCurrentUser(); const campaigns = useCampaigns(); const create = useCreateCampaign(); const preview = useCampaignPreview(); const action = useCampaignAction();
  const canCreate = hasPermission(user.data?.roles, Permission.CREATE_CAMPAIGN); const canApprove = hasPermission(user.data?.roles, Permission.APPROVE_CAMPAIGN);
  const [input, setInput] = useState<CampaignInput>(initial); const [showForm, setShowForm] = useState(false);
  const update = <K extends keyof CampaignInput>(key: K, value: CampaignInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const submit = () => create.mutate({ ...input, schedule: { ...input.schedule, scheduledAt: new Date(input.schedule.scheduledAt).toISOString() } }, { onSuccess: () => { setShowForm(false); setInput(initial()); } });
  return <div className="px-4 py-6 md:px-8"><AdminPageHeader title="Campaigns" description="Product-only notifications use an immutable, independently approved audience and message." />
    {canCreate && <div className="mt-5"><Button onClick={() => setShowForm((value) => !value)}>{showForm ? "Close composer" : "Create campaign"}</Button></div>}
    {showForm && <section className="mt-5 max-w-3xl rounded-md border border-border bg-surface p-5"><div className="grid gap-3"><label className="grid gap-1 text-sm">Internal name<input className="min-h-10 rounded border px-3" value={input.name} onChange={(event) => update("name", event.target.value)} /></label><label className="grid gap-1 text-sm">Objective<select className="min-h-10 rounded border px-3" value={input.objective} onChange={(event) => update("objective", event.target.value as CampaignInput["objective"])}><option value="ANNOUNCEMENT">Announcement</option><option value="ONBOARDING">Onboarding</option><option value="REENGAGEMENT">Re-engagement</option></select></label><label className="grid gap-1 text-sm">Title<input className="min-h-10 rounded border px-3" maxLength={80} value={input.title} onChange={(event) => update("title", event.target.value)} /></label><label className="grid gap-1 text-sm">Message<textarea className="min-h-24 rounded border p-3" maxLength={240} value={input.body} onChange={(event) => update("body", event.target.value)} /></label><label className="grid gap-1 text-sm">Deep link<select className="min-h-10 rounded border px-3" value={input.deepLink} onChange={(event) => update("deepLink", event.target.value as CampaignInput["deepLink"])}><option value="/explore">Explore</option><option value="/onboarding">Onboarding</option><option value="/account">Account</option><option value="/">Home</option></select></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Audience<select className="min-h-10 rounded border px-3" value={input.audience.target} onChange={(event) => update("audience", { ...input.audience, target: event.target.value as "SIGNED_IN" | "ANONYMOUS" })}><option value="SIGNED_IN">Signed-in readers</option><option value="ANONYMOUS">Unsigned installers</option></select></label><label className="grid gap-1 text-sm">Inactive for days (optional)<input className="min-h-10 rounded border px-3" type="number" min="0" value={input.audience.inactiveDays ?? ""} onChange={(event) => update("audience", { ...input.audience, inactiveDays: event.target.value ? Number(event.target.value) : undefined })} /></label></div><label className="grid gap-1 text-sm">Scheduled at<input className="min-h-10 rounded border px-3" type="datetime-local" value={input.schedule.scheduledAt} onChange={(event) => update("schedule", { ...input.schedule, scheduledAt: event.target.value })} /></label><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={preview.isPending} onClick={() => preview.mutate(input.audience)}>Preview audience</Button><Button disabled={create.isPending || !input.name || !input.title || !input.body} onClick={submit}>{create.isPending ? "Saving…" : "Create draft"}</Button>{preview.data && <span className="self-center text-sm text-muted-foreground">Eligible now: {preview.data.eligible}</span>}</div><MutationError error={create.error ?? preview.error} /></div></section>}
    <section className="mt-8 overflow-x-auto rounded-md border border-border bg-surface"><table className="w-full min-w-[55rem] text-sm"><thead className="border-b bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Creator / approver</th><th className="px-4 py-3">Runs</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{campaigns.data?.map((campaign) => <tr className="border-b last:border-0" key={campaign.id}><td className="px-4 py-3"><p className="font-medium">{campaign.name}</p><p className="mt-1 text-xs text-muted-foreground">{campaign.activeVersion?.title}</p></td><td className="px-4 py-3"><span className="rounded bg-muted px-2 py-1 text-xs">{campaign.status}</span></td><td className="px-4 py-3 text-xs text-muted-foreground">{campaign.activeVersion?.createdBy.email}{campaign.activeVersion?.approvedBy ? ` / ${campaign.activeVersion.approvedBy.email}` : ""}</td><td className="px-4 py-3">{campaign._count.runs}</td><td className="px-4 py-3 text-right"><div className="flex justify-end gap-2">{canCreate && campaign.status === "DRAFT" && campaign.activeVersion?.createdBy.email === user.data?.email && <Button size="sm" variant="outline" onClick={() => action.mutate({ id: campaign.id, action: "submit" })}>Submit</Button>}{canApprove && campaign.status === "PENDING_APPROVAL" && campaign.activeVersion?.createdBy.email !== user.data?.email && <Button size="sm" onClick={() => action.mutate({ id: campaign.id, action: "approve" })}>Approve</Button>}{(canApprove || hasPermission(user.data?.roles, Permission.MANAGE_PLATFORM)) && ["SCHEDULED", "RUNNING"].includes(campaign.status) && <Button size="sm" variant="destructive" onClick={() => action.mutate({ id: campaign.id, action: "pause" })}>Pause</Button>}</div></td></tr>)}</tbody></table>{!campaigns.data?.length && <p className="p-6 text-sm text-muted-foreground">No campaigns yet.</p>}</section><MutationError error={action.error} /></div>;
}
