import { useEffect, useState } from "react";
import { useLocalSearchParams, Link } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import NetInfo from "@react-native-community/netinfo";
import { Share, Text, View } from "react-native";
import { api } from "@/src/lib/api";
import { requestCaptcha } from "@/src/lib/captcha";
import { cacheRead, cacheWrite, enqueue } from "@/src/lib/offline";
import type { Comment, Page, Publication } from "@/src/lib/models";
import { Action, ErrorText, Field, Loading, Notice, Screen, Subtitle, styles } from "@/src/components/ui";

const mutationId = () => `mutation-${Date.now()}-${Math.random().toString(16).slice(2)}`;
export default function NoteScreen() {
  const { id, captchaToken } = useLocalSearchParams<{ id: string; captchaToken?: string }>();
  const query = useQuery({ queryKey: ["note", id], enabled: Boolean(id), queryFn: async () => { try { const note = await api<Publication>(`/publications/${id}`); cacheWrite(`note:${id}`, note); void api(`/publications/${id}/view`, { method: "POST", body: JSON.stringify({}), visitor: true }); return note; } catch { return cacheRead<Publication>(`note:${id}`); } } });
  const comments = useQuery({ queryKey: ["comments", id], enabled: Boolean(id), queryFn: async () => { try { const page = await api<Page<Comment>>(`/publications/${id}/comments?page=1&pageSize=30`); cacheWrite(`comments:${id}`, page); return page; } catch { return cacheRead<Page<Comment>>(`comments:${id}`) ?? { data: [], meta: { page: 1, pageSize: 30, total: 0 } }; } } });
  const [bookmarked, setBookmarked] = useState(false); const [body, setBody] = useState(""); const [anonymous, setAnonymous] = useState(false); const [name, setName] = useState(""); const [reportReason, setReportReason] = useState(""); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>();
  useEffect(() => { api<{ publication: { id: string } }[]>("/bookmarks").then((rows) => setBookmarked(rows.some((row) => row.publication.id === id))).catch(() => undefined); }, [id]);
  if (query.isLoading || !comments.data) return <Loading label="Loading note…" />;
  if (!query.data) return <Screen><ErrorText>This note is unavailable offline.</ErrorText></Screen>;
  const note = query.data;
  const reversible = async (path: string, method: string, payload: unknown) => { const online = (await NetInfo.fetch()).isConnected; if (!online) { enqueue({ id: mutationId(), method, path, body: payload, createdAt: Date.now() }); setNotice("Saved on this device — it will sync when you reconnect."); return; } await api(path, { method, body: JSON.stringify(payload), idempotencyKey: mutationId() }); };
  const toggleBookmark = async () => { try { if (bookmarked) await reversible(`/bookmarks/${id}`, "DELETE", {}); else await reversible("/bookmarks", "POST", { publicationId: id }); setBookmarked(!bookmarked); } catch (e) { setError(e instanceof Error ? e.message : "Could not update bookmark."); } };
  const postComment = async () => { if (!body.trim()) return; if (!captchaToken) { setNotice("Complete the quick verification, then return here to post your comment."); await requestCaptcha(`note/${id}`); return; } try { await reversible(`/publications/${id}/comments`, "POST", { body, isAnonymous: anonymous, displayName: anonymous ? name || undefined : undefined, captchaToken }); setBody(""); setNotice("Comment submitted."); await comments.refetch(); } catch (e) { setError(e instanceof Error ? e.message : "Could not post comment."); } };
  const report = async () => { if (!reportReason.trim()) return; try { await reversible(`/publications/${id}/report`, "POST", { reason: reportReason }); setReportReason(""); setNotice("Thanks. Your report has been submitted."); } catch (e) { setError(e instanceof Error ? e.message : "Could not submit report."); } };
  return <Screen><Text style={{ fontSize: 28, fontWeight: "700" }}>{note.title}</Text>{note.author ? <Link href={`/profile/${note.author.username}`}>by {note.author.displayName}</Link> : <Subtitle>Anonymous</Subtitle>}<Subtitle>{note.publishedAt ? new Date(note.publishedAt).toLocaleDateString() : "Pending publication"}</Subtitle><Text selectable style={{ fontSize: 17, lineHeight: 27 }}>{note.content}</Text>{note.tags.map((tag) => <Text key={tag} style={{ color: "#57534e" }}>#{tag}</Text>)}<View style={styles.row}><Action title={bookmarked ? "Remove bookmark" : "Bookmark"} tone="secondary" onPress={() => void toggleBookmark()} /><Action title="Share" tone="secondary" onPress={() => void Share.share({ title: note.title, url: `https://noteschain.org/p/${id}` })} /></View>{note.chain?.explorerUrl && <Action title="View blockchain proof" tone="secondary" onPress={() => { void Share.share({ message: note.chain!.explorerUrl! }); }} />}{notice && <Notice>{notice}</Notice>}{error && <ErrorText>{error}</ErrorText>}<View style={styles.divider} /><Text style={{ fontSize: 21, fontWeight: "700" }}>Comments</Text>{note.commentsEnabled ? <><Field multiline placeholder="Add a thoughtful comment" value={body} onChangeText={setBody} style={[styles.field, { minHeight: 100, textAlignVertical: "top" }]} /><View style={styles.row}><Action title={anonymous ? "Posting anonymously" : "Post with account"} tone="secondary" onPress={() => setAnonymous(!anonymous)} /></View>{anonymous && <Field placeholder="Display name (optional)" value={name} onChangeText={setName} />}<Action title={captchaToken ? "Post comment" : "Verify & post comment"} onPress={() => void postComment()} /></> : <Subtitle>Comments are disabled for this note.</Subtitle>}{comments.data.data.map((comment) => <View key={comment.id} style={styles.card}><Text style={{ fontWeight: "700" }}>{comment.isAnonymous ? comment.displayName || "Anonymous" : comment.author?.displayName || "NotesChain reader"}</Text><Text>{comment.body}</Text><Subtitle>{new Date(comment.createdAt).toLocaleString()}</Subtitle></View>)}<View style={styles.divider} /><Text style={{ fontSize: 18, fontWeight: "700" }}>Report this note</Text><Field multiline placeholder="What needs attention?" value={reportReason} onChangeText={setReportReason} style={[styles.field, { minHeight: 90, textAlignVertical: "top" }]} /><Action title="Send report" tone="secondary" onPress={() => void report()} /></Screen>;
}
