import { useEffect, useRef, useState } from "react";
import { useLocalSearchParams, router } from "expo-router";
import NetInfo from "@react-native-community/netinfo";
import { Alert, Text, View } from "react-native";
import { api } from "@/src/lib/api";
import { cacheRead, cacheWrite, enqueue } from "@/src/lib/offline";
import type { Draft, Identity } from "@/src/lib/models";
import { Action, ErrorText, Field, Loading, Notice, Screen, Subtitle, Title, styles } from "@/src/components/ui";

const editable = (status: string) => status === "DRAFT" || status === "CHANGES_REQUESTED";
const saveKey = () => `draft-save-${Date.now()}-${Math.random().toString(16).slice(2)}`;

export default function DraftEditorScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [draft, setDraft] = useState<Draft | null>(); const [identities, setIdentities] = useState<Identity[]>([]);
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [tags, setTags] = useState(""); const [identityMode, setIdentityMode] = useState<Draft["identityMode"]>("ANONYMOUS"); const [identityId, setIdentityId] = useState<string | null>(null); const [discoverability, setDiscoverability] = useState<Draft["discoverability"]>("PUBLIC");
  const [saveState, setSaveState] = useState("Saved"); const [error, setError] = useState<string>(); const latest = useRef({ title, content });
  useEffect(() => { latest.current = { title, content }; }, [title, content]);
  useEffect(() => { if (!id) return; (async () => { try { const remote = await api<Draft>(`/drafts/${id}`); cacheWrite(`draft:${id}`, remote); setDraft(remote); setTitle(remote.title); setContent(remote.content); setTags(remote.tags.join(", ")); setIdentityMode(remote.identityMode); setIdentityId(remote.publicIdentityId); setDiscoverability(remote.discoverability); setIdentities(await api<Identity[]>("/identities")); } catch { const offline = cacheRead<Draft>(`draft:${id}`); setDraft(offline); if (offline) { setTitle(offline.title); setContent(offline.content); setTags(offline.tags.join(", ")); setIdentityMode(offline.identityMode); setIdentityId(offline.publicIdentityId); setDiscoverability(offline.discoverability); } } })(); }, [id]);
  useEffect(() => { if (!id || !draft || !editable(draft.status)) return; const timer = setTimeout(() => { void autosave(); }, 1200); return () => clearTimeout(timer); }, [title, content]);
  const metadata = () => ({ tags: tags.split(",").map((tag) => tag.trim().toLowerCase()).filter(Boolean), identityMode, publicIdentityId: identityMode === "ANONYMOUS" ? null : identityId, discoverability });
  const autosave = async () => { if (!id || !draft || !editable(draft.status)) return; const online = (await NetInfo.fetch()).isConnected; if (!online) { enqueue({ id: saveKey(), method: "POST", path: `/drafts/${id}/autosave`, body: latest.current, createdAt: Date.now() }); cacheWrite(`draft:${id}`, { ...draft, ...latest.current, updatedAt: new Date().toISOString() }); setSaveState("Saved on this device — sync queued"); return; }
    try { setSaveState("Saving…"); const saved = await api<Draft>(`/drafts/${id}/autosave`, { method: "POST", body: JSON.stringify(latest.current), idempotencyKey: saveKey() }); cacheWrite(`draft:${id}`, saved); setDraft(saved); setSaveState("Saved"); } catch { setSaveState("Could not save — retrying when online"); }
  };
  const updateMetadata = async () => { if (!id || !draft || !editable(draft.status)) return; try { const saved = await api<Draft>(`/drafts/${id}`, { method: "PATCH", body: JSON.stringify(metadata()), idempotencyKey: saveKey() }); cacheWrite(`draft:${id}`, saved); setDraft(saved); } catch (e) { setError(e instanceof Error ? e.message : "Could not update draft settings."); } };
  const submit = async () => { if (!id) return; if (!title.trim() || !content.trim()) { setError("A title and body are required before submission."); return; } if (identityMode !== "ANONYMOUS" && !identityId) { setError("Choose a public identity, or publish anonymously."); return; } try { await autosave(); await updateMetadata(); const saved = await api<Draft>(`/drafts/${id}/submit`, { method: "POST", idempotencyKey: saveKey() }); setDraft(saved); Alert.alert("Submitted", "Your note is now awaiting review."); } catch (e) { setError(e instanceof Error ? e.message : "Could not submit this draft."); } };
  const publish = () => Alert.alert("Publish permanently?", "This action writes the approved note to the publication process and cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", style: "destructive", onPress: async () => { try { const publication = await api<{ id: string }>(`/drafts/${id}/confirm-publish`, { method: "POST", body: JSON.stringify({ acknowledgeIrreversible: true }), idempotencyKey: saveKey() }); router.replace(`/note/${publication.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Could not publish this note."); } } }]);
  if (draft === undefined) return <Loading label="Loading your draft…" />;
  if (!draft) return <Screen><ErrorText>This draft is unavailable. Connect once to load it on this device.</ErrorText></Screen>;
  const canEdit = editable(draft.status);
  return <Screen><Title>{canEdit ? "Edit draft" : "Your submission"}</Title><Subtitle>{saveState}</Subtitle>{draft.status === "PENDING_REVIEW" && <Notice>Awaiting moderator review. You can withdraw it from the website for now.</Notice>}{draft.status === "APPROVED" && <Notice>Approved — you can now publish permanently while online.</Notice>}{draft.status === "REJECTED" && <Notice>This submission was rejected. Read any moderation feedback on the website.</Notice>}<Field editable={canEdit} placeholder="Title" value={title} onChangeText={setTitle} /><Field editable={canEdit} multiline placeholder="What’s on your mind?" value={content} onChangeText={setContent} style={[styles.field, { minHeight: 260, textAlignVertical: "top" }]} />{canEdit && <><Subtitle>{Array.from(content).length.toLocaleString()} characters</Subtitle><Field placeholder="Tags, separated by commas" value={tags} onChangeText={setTags} onBlur={() => void updateMetadata()} /><Text style={{ fontWeight: "700" }}>Identity</Text><View style={styles.row}><Action title="Anonymous" tone={identityMode === "ANONYMOUS" ? "primary" : "secondary"} onPress={() => { setIdentityMode("ANONYMOUS"); setIdentityId(null); }} /><Action title="Named" tone={identityMode === "NAMED" ? "primary" : "secondary"} onPress={() => setIdentityMode("NAMED")} /></View>{identityMode !== "ANONYMOUS" && (identities.length ? identities.map((identity) => <Action key={identity.id} title={`${identity.displayName} (@${identity.username})`} tone={identityId === identity.id ? "primary" : "secondary"} onPress={() => setIdentityId(identity.id)} />) : <Subtitle>Create an identity before publishing under a name.</Subtitle>)}<Text style={{ fontWeight: "700" }}>Visibility</Text><View style={styles.row}><Action title="Public" tone={discoverability === "PUBLIC" ? "primary" : "secondary"} onPress={() => setDiscoverability("PUBLIC")} /><Action title="Unlisted" tone={discoverability === "UNLISTED" ? "primary" : "secondary"} onPress={() => setDiscoverability("UNLISTED")} /></View><Action title="Save settings" tone="secondary" onPress={() => void updateMetadata()} /><Action title="Submit for review" onPress={() => void submit()} /></>}{draft.status === "APPROVED" && <Action title="Publish permanently" tone="danger" onPress={publish} />}{error && <ErrorText>{error}</ErrorText>}</Screen>;
}
